### ISSUE TITLE
Plugin No Longer Works

### ISSUE THREAD

**Issue by obajide** [PaystackHQ/plugin-engine-themes-directory-engine-freelance-engine#1]
Hi,
This plugin no longer works with the Engine.
Can an update be done.

Regards.

**Comment by Kendysond** [comment]
Hi Jide, 

Apologies for the extremely tardy update. 

Here's the update -- https://github.com/Kendysond/Paystack-Gateway-for-Enginethemes.com-FreelanceEngine-site-1.7-1.8- 

I hope this helps.
