### ISSUE TITLE
Error on Redirecting After Payment

### ISSUE THREAD

**Issue by steveamaza** [PaystackHQ/plugin-engine-themes-directory-engine-freelance-engine#2]
After payment is successful via Paystack, user gets presented with a 404 error on redirecting to the `../process-payment/..` page.

Here is a screenshot that demonstrates this behaviour
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/15840315/32546663-213c034e-c480-11e7-8087-d372311e7aef.png">

Here is the correct behavior when user pays with cash, for example
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/15840315/32546782-74849fe8-c480-11e7-955a-3d0b2dd35262.png">

**Comment by Kendysond** [comment]
Hi @steveamaza, 

Advice the guy to use the updated version of the plugin:  https://github.com/PaystackHQ/Paystack-Gateway-for-Enginethemes.com-FreelanceEngine-site-1.7-1.8- 

I think the version he is using is incompatible with his theme's version.

**Comment by steveamaza** [comment]
Thanks for coming through real quick @Kendysond. I have reached out to him and will give you feedback in a few minutes

**Comment by steveamaza** [comment]
Thanks Douglas. It works perfectly.
