### ISSUE TITLE
Not working with Freelaneengine

### ISSUE THREAD

**Issue by seunafara** [PaystackHQ/plugin-engine-themes-directory-engine-freelance-engine#3]
Hi, your plugin leaves an error 404 page after payment is successful and it doesn't record the payment in the backend either. Not working 100% please fix

**Comment by ibrahimlawal** [comment]
Hey @reckez it can really be frustrating using a plugin that seems not to work. Here are some questions that can help us check the issue:

What URL are you redirected to which gives 404?
What version of the FreelanceEngine do you have installed?
What version of Wordpress do you have installed?

Please provide answers so we can do some troubleshooting.

If you have a staging site, you can provide the url so we make a test transaction to check too.

Thank you for choosing Paystack!

Thanks!

**Comment by seunafara** [comment]
thanks for the quick response. I already found a fix myself. Thank you

**Comment by ibrahimlawal** [comment]
Awesome one @reckez . What was the fix? Kindly share so anyone else facing same issue can benefit.

**Comment by seunafara** [comment]
Hi, I apologise for the late reply. The fix can be found here
https://github.com/PaystackHQ/paystack-gateway-for-enginethemes-freelanceengine1.7-1.8

**Comment by ibrahimlawal** [comment]
Oh I see! You installed the correct version for your theme! Nice!

**Comment by seunafara** [comment]
Hi Ibrahim, The correct version of the plugin was working great till
recently. My theme was not updated neither was the plugin. I've tried
deactivating all my plugins but still the particular error doesn't go off.
Everytime I try to checkout with Paystack (i.e deposit funds) instead of
getting the add card info page, I get a bad request page and nothing
happens. Can you please offer to look into this problem ASAP? Thank you.

**Comment by ibrahimlawal** [comment]
@reckez where can I test?

**Comment by seunafara** [comment]
Hi, can i get your email address in order to send you the backend login details so you can have a proper look or you wouldn't be needing that??

**Comment by ibrahimlawal** [comment]
support@paystack.com . `ATTN: Ibrahim` in the subject.

**Comment by steveamaza** [comment]
Plugin works now. Seems an external bug
